using Nivara.Operations;
using Nivara.Tensors;
using NUnit.Framework;
using System.Text.Json;

namespace Nivara.Tests.Query;

/// <summary>
/// Cross-validates Nivara's quantile, rolling-mean, rank/percent-rank, and stddev
/// implementations against Polars reference fixtures committed to
/// samples/data/polars-incident/manifest.json (generated by
/// samples/NivaraIncident/Python/gen_reference.py).
/// </summary>
/// <remarks>
/// Unlike the generic Polars*CrossValidationTests which use small fixed arrays,
/// these fixtures exercise the same APIs on realistic incident telemetry
/// distributions (latency in ms, error rates as percentages) across multiple
/// services.
/// </remarks>
[TestFixture]
public class PolarsIncidentCrossValidationTests
{
    const double Tolerance = 1e-9;

    internal static string FixtureDir => Path.Combine(
        TestContext.CurrentContext.TestDirectory,
        "..", "..", "..", "..", "..", "samples", "data", "polars-incident");

    [Test]
    public void IncidentFixtures_MatchesPolarsReference()
    {
        var manifestPath = Path.Combine(FixtureDir, "manifest.json");
        Assert.That(File.Exists(manifestPath), Is.True, $"Missing reference file: {manifestPath}");

        using var doc = JsonDocument.Parse(File.ReadAllBytes(manifestPath));
        var cases = doc.RootElement.EnumerateArray().ToList();
        Assert.That(cases, Is.Not.Empty, "manifest has no cases");

        foreach (var caseEl in cases)
        {
            var name = caseEl.GetProperty("name").GetString()!;
            var kind = caseEl.GetProperty("kind").GetString()!;

            switch (kind)
            {
                case "quantile_per_service":
                    AssertQuantilePerService(name, caseEl);
                    break;
                case "rolling_per_service":
                    AssertRollingPerService(name, caseEl);
                    break;
                case "rank_per_service":
                    AssertRankPerService(name, caseEl);
                    break;
                case "stddev_per_service":
                    AssertStdDevPerService(name, caseEl);
                    break;
                default:
                    Assert.Fail($"{name}: unknown kind '{kind}'");
                    break;
            }
        }
    }

    static void AssertQuantilePerService(string name, JsonElement caseEl)
    {
        var q = caseEl.GetProperty("q").GetDouble();
        var services = caseEl.GetProperty("services");
        var expected = caseEl.GetProperty("expected");

        foreach (var svcProp in services.EnumerateObject())
        {
            var svcName = svcProp.Name;
            var values = svcProp.Value.EnumerateArray()
                .Select(e => e.ValueKind == JsonValueKind.Null ? (double?)null : e.GetDouble())
                .ToArray();

            using var series = new NivaraSeries<double>(NivaraColumn.CreateFromNullable(values));
            var actual = series.Quantile(q);
            var exp = expected.GetProperty(svcName).GetDouble();

            Assert.That(actual, Is.EqualTo(exp).Within(Tolerance),
                $"{name}: Quantile({q}) for {svcName} mismatch");
        }
    }

    static void AssertRollingPerService(string name, JsonElement caseEl)
    {
        int windowSize = (int)caseEl.GetProperty("window_size").GetInt64();
        int minSamples = (int)caseEl.GetProperty("min_samples").GetInt64();
        var services = caseEl.GetProperty("services");
        var expectedMeans = caseEl.GetProperty("expected_rolling_mean");

        foreach (var svcProp in services.EnumerateObject())
        {
            var svcName = svcProp.Name;
            var values = svcProp.Value.EnumerateArray()
                .Select(e => e.ValueKind == JsonValueKind.Null ? (double?)null : e.GetDouble())
                .ToArray();

            var columns = new Dictionary<string, IColumn>(StringComparer.OrdinalIgnoreCase)
            {
                ["v"] = NivaraColumn.CreateFromNullable(values),
            };

            var spec = new WindowSpec();
            var result = PartitionedWindowEngine.Compute(
                columns, columns["v"], spec,
                c => ((NivaraColumn<double>)c).RollingMean(windowSize, minSamples));

            var expected = expectedMeans.GetProperty(svcName).EnumerateArray()
                .Select(e => e.ValueKind == JsonValueKind.Null ? (double?)null : e.GetDouble())
                .ToArray();

            Assert.That(result, Is.InstanceOf<NivaraColumn<double>>(),
                $"{name}: RollingMean for {svcName} type mismatch");
            Assert.That(result.Length, Is.EqualTo(expected.Length),
                $"{name}: RollingMean for {svcName} length mismatch");

            var resultCol = (NivaraColumn<double>)result;
            for (int i = 0; i < result.Length; i++)
            {
                var exp = expected[i];
                Assert.That(resultCol.IsNull(i), Is.EqualTo(exp is null),
                    $"{name}: RollingMean for {svcName} null mask mismatch at row {i}");
                if (exp is not null)
                    Assert.That(Math.Abs(resultCol[i] - exp.Value), Is.LessThan(1e-6),
                        $"{name}: RollingMean for {svcName} mismatch at row {i} (expected {exp:G12}, actual {resultCol[i]:G12})");
            }
        }
    }

    static void AssertRankPerService(string name, JsonElement caseEl)
    {
        var services = caseEl.GetProperty("services");
        var expectedRank = caseEl.GetProperty("expected_rank");
        var expectedDense = caseEl.GetProperty("expected_dense_rank");
        var expectedPct = caseEl.GetProperty("expected_percent_rank");

        // Build a flat list of (service, delta) for non-null deltas, preserving order
        var svcNames = new List<string>();
        var deltas = new List<long?>();
        foreach (var svcProp in services.EnumerateObject())
        {
            if (svcProp.Value.ValueKind != JsonValueKind.Null)
            {
                svcNames.Add(svcProp.Name);
                deltas.Add(svcProp.Value.GetInt64());
            }
        }

        var columns = new Dictionary<string, IColumn>(StringComparer.OrdinalIgnoreCase)
        {
            ["v"] = NivaraColumn.CreateFromNullable(deltas.ToArray()),
        };

        var partitionBy = Array.Empty<string>();
        var orderBy = new List<SortKey> { new("v", SortDirection.Descending) };

        // Rank
        var rankResult = RankKernel.Compute(columns, partitionBy, orderBy, RankKind.Rank);
        Assert.That(rankResult, Is.InstanceOf<NivaraColumn<long>>(), $"{name}: rank type mismatch");
        var rankCol = (NivaraColumn<long>)rankResult;
        for (int i = 0; i < svcNames.Count; i++)
        {
            var exp = expectedRank.GetProperty(svcNames[i]).GetInt64();
            Assert.That(rankCol[i], Is.EqualTo(exp),
                $"{name}: rank for {svcNames[i]} mismatch");
        }

        // DenseRank
        var denseResult = RankKernel.Compute(columns, partitionBy, orderBy, RankKind.DenseRank);
        Assert.That(denseResult, Is.InstanceOf<NivaraColumn<long>>(), $"{name}: dense_rank type mismatch");
        var denseCol = (NivaraColumn<long>)denseResult;
        for (int i = 0; i < svcNames.Count; i++)
        {
            var exp = expectedDense.GetProperty(svcNames[i]).GetInt64();
            Assert.That(denseCol[i], Is.EqualTo(exp),
                $"{name}: dense_rank for {svcNames[i]} mismatch");
        }

        // PercentRank
        var pctResult = RankKernel.Compute(columns, partitionBy, orderBy, RankKind.PercentRank);
        Assert.That(pctResult, Is.InstanceOf<NivaraColumn<double>>(), $"{name}: percent_rank type mismatch");
        var pctCol = (NivaraColumn<double>)pctResult;
        for (int i = 0; i < svcNames.Count; i++)
        {
            var exp = expectedPct.GetProperty(svcNames[i]).GetDouble();
            Assert.That(Math.Abs(pctCol[i] - exp), Is.LessThan(Tolerance),
                $"{name}: percent_rank for {svcNames[i]} mismatch (expected {exp:G12}, actual {pctCol[i]:G12})");
        }

        // Verify null services produce null ranks
        foreach (var svcProp in services.EnumerateObject())
        {
            if (svcProp.Value.ValueKind == JsonValueKind.Null)
            {
                Assert.That(expectedRank.GetProperty(svcProp.Name).ValueKind, Is.EqualTo(JsonValueKind.Null),
                    $"{name}: {svcProp.Name} should have null rank");
            }
        }
    }

    static void AssertStdDevPerService(string name, JsonElement caseEl)
    {
        var ddof = caseEl.GetProperty("ddof").GetInt32();
        var services = caseEl.GetProperty("services");
        var expected = caseEl.GetProperty("expected");

        foreach (var svcProp in services.EnumerateObject())
        {
            var svcName = svcProp.Name;
            var values = svcProp.Value.EnumerateArray()
                .Select(e => e.ValueKind == JsonValueKind.Null ? (double?)null : e.GetDouble())
                .ToArray();

            using var series = new NivaraSeries<double>(NivaraColumn.CreateFromNullable(values));
            var actual = series.StdDev(ddof);
            var exp = expected.GetProperty(svcName).GetDouble();

            Assert.That(actual, Is.EqualTo(exp).Within(Tolerance),
                $"{name}: StdDev(ddof={ddof}) for {svcName} mismatch");
        }
    }
}
