using Nivara.Operations;
using NUnit.Framework;
using System.Text.Json;

namespace Nivara.Tests.Query;

/// <summary>
/// Cross-validates Nivara's variance/standard-deviation implementation against numpy/polars
/// reference fixtures committed to samples/data/polars-moments/manifest.json (generated by
/// samples/NivaraIncident/Python/gen_reference.py).
/// </summary>
/// <remarks>
/// polars Series.std/var with an explicit ddof are numerically identical to numpy np.std/np.var
/// (same sum-of-squared-deviation over n - ddof definition). ddof=0 is population (divide by n),
/// ddof=1 is sample (divide by n - 1). Null values are excluded from the computation.
/// </remarks>
[TestFixture]
public class PolarsMomentsCrossValidationTests
{
    const double Tolerance = 1e-9;

    internal static string FixtureDir => Path.Combine(
        TestContext.CurrentContext.TestDirectory,
        "..", "..", "..", "..", "..", "samples", "data", "polars-moments");

    [Test]
    public void StdDevVariance_MatchesNumpyPolarsFixtures()
    {
        var manifestPath = Path.Combine(FixtureDir, "manifest.json");
        Assert.That(File.Exists(manifestPath), Is.True, $"Missing reference file: {manifestPath}");

        using var doc = JsonDocument.Parse(File.ReadAllBytes(manifestPath));
        var cases = doc.RootElement.EnumerateArray().ToList();
        Assert.That(cases, Is.Not.Empty, "manifest has no cases");

        foreach (var caseEl in cases)
        {
            var name = caseEl.GetProperty("name").GetString()!;
            var kind = caseEl.GetProperty("kind").GetString()!;
            var ddof = caseEl.GetProperty("ddof").GetInt32();
            var expected = caseEl.GetProperty("value").GetDouble();
            var values = caseEl.GetProperty("v").EnumerateArray()
                .Select(e => e.ValueKind == JsonValueKind.Null ? (double?)null : e.GetDouble())
                .ToArray();

            using var series = new NivaraSeries<double>(NivaraColumn.CreateFromNullable(values));

            if (kind == "stddev")
            {
                Assert.That(series.StdDev(ddof), Is.EqualTo(expected).Within(Tolerance),
                    $"{name}: StdDev({ddof}) mismatch");
            }
            else
            {
                Assert.That(kind, Is.EqualTo("variance"), $"{name}: unknown kind");
                Assert.That(series.Variance(ddof), Is.EqualTo(expected).Within(Tolerance),
                    $"{name}: Variance({ddof}) mismatch");
            }

            AssertSampleDeviationMatchesPopulation(name, kind, values);
        }
    }

    // Sample (ddof=1) variance/stddev must equal population values scaled by n/(n-1).
    static void AssertSampleDeviationMatchesPopulation(string name, string kind, double?[] values)
    {
        var validCount = values.Count(v => v.HasValue);
        if (validCount < 2)
            return;

        using var series = new NivaraSeries<double>(NivaraColumn.CreateFromNullable(values));
        var population = kind == "stddev" ? series.StdDev(0) : series.Variance(0);
        var sample = kind == "stddev" ? series.StdDev(1) : series.Variance(1);

        if (kind == "stddev")
        {
            Assert.That(sample * sample, Is.EqualTo(population * population * validCount / (validCount - 1d)).Within(Tolerance * 10),
                $"{name}: sample StdDev should be population scaled by n/(n-1)");
        }
        else
        {
            Assert.That(sample, Is.EqualTo(population * validCount / (validCount - 1d)).Within(Tolerance * 10),
                $"{name}: sample Variance should be population scaled by n/(n-1)");
        }
    }
}
