using Nivara.Operations;
using NUnit.Framework;
using System.Text.Json;

namespace Nivara.Tests.Query;

/// <summary>
/// Cross-validates Nivara's quantile/median implementation against Polars reference fixtures
/// committed to samples/data/polars-quantile/manifest.json (generated by
/// samples/NivaraIncident/Python/gen_reference.py).
/// </summary>
/// <remarks>
/// Polars quantile(interpolation="linear") is Hyndman-Fan type 7 linear interpolation, which is
/// exactly what Nivara implements. Null values are excluded from the computation. The median is
/// Quantile(0.5), so even-length series average the two middle values.
/// </remarks>
[TestFixture]
public class PolarsQuantileCrossValidationTests
{
    const double Tolerance = 1e-9;

    internal static string FixtureDir => Path.Combine(
        TestContext.CurrentContext.TestDirectory,
        "..", "..", "..", "..", "..", "samples", "data", "polars-quantile");

    [Test]
    public void QuantileMedian_MatchesPolarsFixtures()
    {
        var manifestPath = Path.Combine(FixtureDir, "manifest.json");
        Assert.That(File.Exists(manifestPath), Is.True, $"Missing reference file: {manifestPath}");

        using var doc = JsonDocument.Parse(File.ReadAllBytes(manifestPath));
        var cases = doc.RootElement.EnumerateArray().ToList();
        Assert.That(cases, Is.Not.Empty, "manifest has no cases");

        foreach (var caseEl in cases)
        {
            var name = caseEl.GetProperty("name").GetString()!;
            var kind = caseEl.GetProperty("kind").GetString()!;
            var values = caseEl.GetProperty("v").EnumerateArray()
                .Select(e => e.ValueKind == JsonValueKind.Null ? (double?)null : e.GetDouble())
                .ToArray();

            using var series = new NivaraSeries<double>(NivaraColumn.CreateFromNullable(values));

            if (kind == "quantile")
            {
                var q = caseEl.GetProperty("q").GetDouble();
                var expected = caseEl.GetProperty("quantile").GetDouble();

                Assert.That(series.Quantile(q), Is.EqualTo(expected).Within(Tolerance),
                    $"{name}: Quantile({q}) mismatch");
            }
            else
            {
                Assert.That(kind, Is.EqualTo("median"), $"{name}: unknown kind");

                var expected = caseEl.GetProperty("median").GetDouble();
                Assert.That(series.Median(), Is.EqualTo(expected).Within(Tolerance),
                    $"{name}: Median() mismatch");

                if (caseEl.TryGetProperty("groups", out var groupsEl))
                {
                    var partition = caseEl.GetProperty("partition").EnumerateArray()
                        .Select(e => e.GetString()).ToArray();
                    AssertPartitionedMedians(name, partition, values, groupsEl);
                }
            }
        }
    }

    static void AssertPartitionedMedians(
        string name, string?[] partition, double?[] values, JsonElement groupsEl)
    {
        var vColumn = NivaraColumn.CreateFromNullable(values);
        var aggregation = AggregationFunctions.Median();

        var groupIndexes = new Dictionary<string, List<int>>();
        for (int i = 0; i < partition.Length; i++)
        {
            var key = partition[i]!;
            if (!groupIndexes.TryGetValue(key, out var indexes))
            {
                indexes = new List<int>();
                groupIndexes[key] = indexes;
            }
            indexes.Add(i);
        }

        foreach (var group in groupsEl.EnumerateObject())
        {
            var expected = group.Value.GetDouble();
            var actual = Convert.ToDouble(aggregation.Apply(vColumn, groupIndexes[group.Name])!);
            Assert.That(actual, Is.EqualTo(expected).Within(Tolerance),
                $"{name}: Median of group {group.Name} mismatch");
        }
    }
}
