using Nivara.Operations;
using Nivara.Tensors;
using NUnit.Framework;
using System.Text.Json;

namespace Nivara.Tests.Query;

/// <summary>
/// Cross-validates the rank-family window kernel (row_number / rank / dense_rank /
/// percent_rank) against Polars reference fixtures committed to
/// samples/data/polars-window/manifest.json (generated by samples/NivaraWindow/gen_reference.py).
/// </summary>
/// <remarks>
/// Polars ranks rows with a null order key as null for every method. Nivara matches that for
/// rank / dense_rank / percent_rank, but row_number intentionally numbers null-key rows LAST in
/// stable partition order (issue #254, SQL semantics) — a documented divergence asserted here on
/// the affected rows, with exact Polars parity everywhere else.
/// </remarks>
[TestFixture]
public class PolarsWindowCrossValidationTests
{
    internal static string FixtureDir => Path.Combine(
        TestContext.CurrentContext.TestDirectory,
        "..", "..", "..", "..", "..", "samples", "data", "polars-window");

    [Test]
    public void RankKernel_MatchesPolarsFixtures()
    {
        var manifestPath = Path.Combine(FixtureDir, "manifest.json");
        Assert.That(File.Exists(manifestPath), Is.True, $"Missing reference file: {manifestPath}");

        using var doc = JsonDocument.Parse(File.ReadAllBytes(manifestPath));
        var cases = doc.RootElement.EnumerateArray().ToList();
        Assert.That(cases, Is.Not.Empty, "manifest has no cases");

        foreach (var caseEl in cases)
        {
            if (caseEl.TryGetProperty("kind", out var kind) && kind.GetString() == "rolling")
                continue;

            var name = caseEl.GetProperty("name").GetString()!;
            var order = caseEl.GetProperty("order").EnumerateArray()
                .Select(e => e.ValueKind == JsonValueKind.Null ? (long?)null : e.GetInt64())
                .ToArray();
            var partition = caseEl.TryGetProperty("partition", out var p) && p.ValueKind == JsonValueKind.Array
                ? p.EnumerateArray().Select(e => e.GetString()).ToArray()
                : null;

            var columns = new Dictionary<string, IColumn>(StringComparer.OrdinalIgnoreCase)
            {
                ["v"] = NivaraColumn.CreateFromNullable(order),
            };
            if (partition is not null)
                columns["g"] = NivaraColumn<string>.CreateForReferenceType(partition!);

            var partitionBy = partition is null ? [] : new[] { "g" };
            var orderBy = new List<SortKey> { new("v") };

            AssertRowNumber(name, order, partition, columns, partitionBy, orderBy, caseEl);
            AssertLongRank(name, RankKind.Rank, columns, partitionBy, orderBy, caseEl, "rank");
            AssertLongRank(name, RankKind.DenseRank, columns, partitionBy, orderBy, caseEl, "dense_rank");
            AssertPercentRank(name, columns, partitionBy, orderBy, caseEl);
        }
    }

    static void AssertRowNumber(
        string name, long?[] order, string?[]? partition,
        IReadOnlyDictionary<string, IColumn> columns, string[] partitionBy,
        IReadOnlyList<SortKey> orderBy, JsonElement caseEl)
    {
        var result = RankKernel.Compute(columns, partitionBy, orderBy, RankKind.RowNumber);
        Assert.That(result, Is.InstanceOf<NivaraColumn<long>>(), $"{name}: row_number type mismatch");

        var reference = caseEl.GetProperty("row_number").EnumerateArray()
            .Select(e => e.ValueKind == JsonValueKind.Null ? (long?)null : e.GetInt64())
            .ToArray();
        Assert.That(result.Length, Is.EqualTo(reference.Length), $"{name}: row_number length mismatch");

        var groups = BuildPartitionRows(partition, order.Length);
        for (int i = 0; i < result.Length; i++)
        {
            var actual = (result as NivaraColumn<long>)![i];
            if (order[i].HasValue)
            {
                Assert.That(actual, Is.EqualTo(reference[i]),
                    $"{name}: row_number mismatch at row {i}");
            }
            else
            {
                var expected = ExpectedRowNumberNullKey(order, groups, i);
                Assert.That(actual, Is.EqualTo(expected),
                    $"{name}: row_number null-key row {i} should be numbered last (SQL divergence, #{nameof(RankKind.RowNumber)})");
                Assert.That(result.IsNull(i), Is.False,
                    $"{name}: row_number null-key row {i} must not be masked");
            }
        }
    }

    static void AssertLongRank(
        string name, RankKind kind, IReadOnlyDictionary<string, IColumn> columns,
        string[] partitionBy, IReadOnlyList<SortKey> orderBy, JsonElement caseEl, string prop)
    {
        var result = RankKernel.Compute(columns, partitionBy, orderBy, kind);
        Assert.That(result, Is.InstanceOf<NivaraColumn<long>>(), $"{name}: {prop} type mismatch");

        var reference = caseEl.GetProperty(prop).EnumerateArray()
            .Select(e => e.ValueKind == JsonValueKind.Null ? (long?)null : e.GetInt64())
            .ToArray();
        Assert.That(result.Length, Is.EqualTo(reference.Length), $"{name}: {prop} length mismatch");

        var values = (NivaraColumn<long>)result;
        for (int i = 0; i < result.Length; i++)
        {
            var expected = reference[i];
            Assert.That(values.IsNull(i), Is.EqualTo(expected is null),
                $"{name}: {prop} null mask mismatch at row {i}");
            if (expected is not null)
                Assert.That(values[i], Is.EqualTo(expected.Value),
                    $"{name}: {prop} mismatch at row {i}");
        }
    }

    static void AssertPercentRank(
        string name, IReadOnlyDictionary<string, IColumn> columns,
        string[] partitionBy, IReadOnlyList<SortKey> orderBy, JsonElement caseEl)
    {
        var result = RankKernel.Compute(columns, partitionBy, orderBy, RankKind.PercentRank);
        Assert.That(result, Is.InstanceOf<NivaraColumn<double>>(), $"{name}: percent_rank type mismatch");

        var reference = caseEl.GetProperty("percent_rank").EnumerateArray()
            .Select(e => e.ValueKind == JsonValueKind.Null ? (double?)null : e.GetDouble())
            .ToArray();
        Assert.That(result.Length, Is.EqualTo(reference.Length), $"{name}: percent_rank length mismatch");

        var values = (NivaraColumn<double>)result;
        for (int i = 0; i < result.Length; i++)
        {
            var expected = reference[i];
            Assert.That(values.IsNull(i), Is.EqualTo(expected is null),
                $"{name}: percent_rank null mask mismatch at row {i}");
            if (expected is not null)
            {
                Assert.That(Math.Abs(values[i] - expected.Value), Is.LessThan(1e-9),
                    $"{name}: percent_rank mismatch at row {i} (expected {expected:G12}, actual {values[i]:G12})");
            }
        }
    }

    // Partitions in first-seen group order; indices within a group preserve row order,
    // mirroring the kernel's hash-based grouping. No partition column => one group.
    static List<List<int>> BuildPartitionRows(string?[]? partition, int rowCount)
    {
        if (partition is null)
            return [Enumerable.Range(0, rowCount).ToList()];

        var groups = new List<List<int>>();
        var index = new Dictionary<string, int>();
        for (int i = 0; i < partition.Length; i++)
        {
            var key = partition[i] ?? "";
            if (!index.TryGetValue(key, out var g))
            {
                g = groups.Count;
                index[key] = g;
                groups.Add([]);
            }
            groups[g].Add(i);
        }
        return groups;
    }

    // Documented #254 divergence: null-key rows are numbered AFTER the valid rows of their
    // partition (validCount + 1 ...), in stable partition (original row) order. Polars emits
    // null there; the fixture's non-null rows already carry the correct 1..validCount values.
    static long ExpectedRowNumberNullKey(long?[] order, List<List<int>> groups, int row)
    {
        foreach (var group in groups)
        {
            if (!group.Contains(row))
                continue;

            int validCount = 0;
            foreach (var r in group)
                if (order[r].HasValue)
                    validCount++;

            int nullIndex = 0;
            foreach (var r in group)
            {
                if (order[r].HasValue)
                    continue;
                if (r == row)
                    return validCount + nullIndex + 1;
                nullIndex++;
            }
        }
        throw new InvalidOperationException($"row {row} not found in any partition");
    }
}
