using Nivara.Operations;
using Nivara.Tensors;
using NUnit.Framework;
using System.Text.Json;

namespace Nivara.Tests.Query;

/// <summary>
/// Cross-validates the rolling window kernel (sum / mean / min / max) against Polars reference
/// fixtures committed to samples/data/polars-window/manifest.json (generated by
/// samples/NivaraIncident/Python/gen_reference.py).
/// </summary>
/// <remarks>
/// Polars skips null values inside the window and emits null when the non-null count in the
/// window is below min_samples; this matches Nivara's minPeriods gating. Partitioned rolling
/// is confined to each group and aligned back to the original rows, matching Nivara's
/// partition slices. Values are authored in rolling (row) order, so no order key is involved.
/// </remarks>
[TestFixture]
public class RollingWindowCrossValidationTests
{
    internal static string FixtureDir => Path.Combine(
        TestContext.CurrentContext.TestDirectory,
        "..", "..", "..", "..", "..", "samples", "data", "polars-window");

    [Test]
    public void RollingKernel_MatchesPolarsFixtures()
    {
        var manifestPath = Path.Combine(FixtureDir, "manifest.json");
        Assert.That(File.Exists(manifestPath), Is.True, $"Missing reference file: {manifestPath}");

        using var doc = JsonDocument.Parse(File.ReadAllBytes(manifestPath));
        var cases = doc.RootElement.EnumerateArray()
            .Where(e => e.TryGetProperty("kind", out var kind) && kind.GetString() == "rolling")
            .ToList();
        Assert.That(cases, Is.Not.Empty, "manifest has no rolling cases");

        foreach (var caseEl in cases)
        {
            var name = caseEl.GetProperty("name").GetString()!;
            var values = caseEl.GetProperty("v").EnumerateArray()
                .Select(e => e.ValueKind == JsonValueKind.Null ? (long?)null : e.GetInt64())
                .ToArray();
            var partition = caseEl.TryGetProperty("partition", out var p) && p.ValueKind == JsonValueKind.Array
                ? p.EnumerateArray().Select(e => e.GetString()).ToArray()
                : null;
            int windowSize = (int)caseEl.GetProperty("window_size").GetInt64();
            int minSamples = (int)caseEl.GetProperty("min_samples").GetInt64();
            var partitionBy = partition is null ? [] : new[] { "g" };

            var columns = new Dictionary<string, IColumn>(StringComparer.OrdinalIgnoreCase)
            {
                ["v"] = NivaraColumn.CreateFromNullable(values),
            };
            if (partition is not null)
                columns["g"] = NivaraColumn<string>.CreateForReferenceType(partition!);

            AssertIntegerColumn(name, "rolling_sum", caseEl,
                ComputeRolling(columns, partitionBy, windowSize, minSamples, c => c.RollingSum(windowSize, minSamples)));
            AssertDoubleColumn(name, "rolling_mean", caseEl,
                ComputeRolling(columns, partitionBy, windowSize, minSamples, c => c.RollingMean(windowSize, minSamples)));
            AssertIntegerColumn(name, "rolling_min", caseEl,
                ComputeRolling(columns, partitionBy, windowSize, minSamples, c => c.RollingMin(windowSize, minSamples)));
            AssertIntegerColumn(name, "rolling_max", caseEl,
                ComputeRolling(columns, partitionBy, windowSize, minSamples, c => c.RollingMax(windowSize, minSamples)));
        }
    }

    static IColumn ComputeRolling(
        IReadOnlyDictionary<string, IColumn> columns, string[] partitionBy,
        int windowSize, int minSamples, Func<NivaraColumn<long>, IColumn> compute)
    {
        var spec = new WindowSpec();
        if (partitionBy.Length > 0)
            spec = spec.PartitionBy(partitionBy);

        return PartitionedWindowEngine.Compute(columns, columns["v"], spec, col => compute((NivaraColumn<long>)col));
    }

    static void AssertIntegerColumn(string name, string prop, JsonElement caseEl, IColumn result)
    {
        var expected = caseEl.GetProperty(prop).EnumerateArray()
            .Select(e => e.ValueKind == JsonValueKind.Null ? (long?)null : e.GetInt64())
            .ToArray();
        Assert.That(result, Is.InstanceOf<NivaraColumn<long>>(), $"{name}: {prop} type mismatch");
        Assert.That(result.Length, Is.EqualTo(expected.Length), $"{name}: {prop} length mismatch");

        var values = (NivaraColumn<long>)result;
        for (int i = 0; i < result.Length; i++)
        {
            var exp = expected[i];
            Assert.That(values.IsNull(i), Is.EqualTo(exp is null),
                $"{name}: {prop} null mask mismatch at row {i}");
            if (exp is not null)
                Assert.That(values[i], Is.EqualTo(exp.Value),
                    $"{name}: {prop} mismatch at row {i} (expected {exp}, actual {values[i]})");
        }
    }

    static void AssertDoubleColumn(string name, string prop, JsonElement caseEl, IColumn result)
    {
        var expected = caseEl.GetProperty(prop).EnumerateArray()
            .Select(e => e.ValueKind == JsonValueKind.Null ? (double?)null : e.GetDouble())
            .ToArray();
        Assert.That(result, Is.InstanceOf<NivaraColumn<double>>(), $"{name}: {prop} type mismatch");
        Assert.That(result.Length, Is.EqualTo(expected.Length), $"{name}: {prop} length mismatch");

        var values = (NivaraColumn<double>)result;
        for (int i = 0; i < result.Length; i++)
        {
            var exp = expected[i];
            Assert.That(values.IsNull(i), Is.EqualTo(exp is null),
                $"{name}: {prop} null mask mismatch at row {i}");
            if (exp is not null)
                Assert.That(Math.Abs(values[i] - exp.Value), Is.LessThan(1e-9),
                    $"{name}: {prop} mismatch at row {i} (expected {exp:G12}, actual {values[i]:G12})");
        }
    }
}
